let ary = [1,2,3,4,5,6,7];
console.log(ary.length);
console.log(ary.toString());
let bol = Array.isArray(ary);
let bb = "sss";
console.log(bol);
console.log(ary[0]);
ary[2] = 300;
console.log(ary[2]);
console.log(ary);
let ind = ary.indexOf(300);
console.log(ind);
ary.push(120);
console.log(ary);
ary.unshift(111);
console.log(ary);
ary.shift(111);
console.log(ary);
ary.splice(2,1);
console.log(ary);
ary.reverse();
console.log(ary);

let a = [100,200,300];
let b = [4,5,6];
let total = a.concat(b);
console.log(total);